Enabled: true
WarningEnabled: true
WarningTempCelsius: 78
WarningMessage: 'The server temperature is high. It may shutdown soon.'
ShutdownEnabled: true
ShutdownTempCelsius: 80
ShutdownMessage: 'The server has exceeded temperature limits. It will now safely shutdown.'
